apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infinispans.infinispan.banzaicloud.com
spec:
  group: infinispan.banzaicloud.com
  names:
    kind: Infinispan
    listKind: InfinispanList
    plural: infinispans
    singular: infinispan
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinispan-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: infinispan-operator
  template:
    metadata:
      labels:
        name: infinispan-operator
    spec:
      containers:
        - name: infinispan-operator
          image: banzaicloud/infinispan-operator
          command:
          - infinispan-operator
          imagePullPolicy: Always
